### ISSUE TITLE
Add project elements

### ISSUE THREAD

**Issue by katieb1** [UBC-MDS/DSCI532_Group204_R#1]
Add all necessary files for the project:

- [x] License

- [x] Code of Conduct

- [x] README (including screenshots of new R plots)

- [x] Contributing

**Comment by katieb1** [comment]
All we need now is to finish the README by adding the screenshots of our plots w/ R code

**Comment by jnederlo** [comment]
Screenshots go in our own repo's, readme is to contain updated sketch, which I will complete.
