### ISSUE TITLE
Add code for all the elements of our app

### ISSUE THREAD

**Issue by katieb1** [UBC-MDS/DSCI532_Group204_R#11]
We need to each add some code for the app, including:

- [x]  app.R file for app layout and dash core components (this is the main app we run)

- [x] barplot.R file for barplot chart function

- [x] choropleth_map.R file for choropleth  chart

- [x]  heatmap.R file for heatmap chart

All of these files should go into the /src folder

**Comment by jnederlo** [comment]
PR #16 adds in the Choropleth Map in `choropleth_maps.r` and Dropdown component in `app.r`

**Comment by katieb1** [comment]
PR # 12 added the bar chart function in barplot.R and a rough app layout (with only bar chart included) - we can merge different versions of the app together later
